# Site
repository: avadacatavra/avadacatavra.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Diane (Duros) Hosfelt
title: Senior Research Engineer
email: dianehosfelt@gmail.com
phone: 412.587.1411
website: https://diane.hosfelt.io

# Social links
twitter_username: avadacatavra 
github_username:  avadacatavra
linkedin_username: dianehosfelt

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a privacy and security researcher in Pittsburgh, PA. Currently, I'm focused on Mixed (Augmented and Virtual) Reality, but I'm also interested in Rust and formal verification

  In my free time, I enjoy bouldering, yoga, traveling, and using Oxford commas. [We](ricky.hosfelt.io) have two cats, [Batman](./assets/batman.jpg) and [Watson](./assets/watson.jpg), who are the cutest cats in the world.



# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Interests and Skills 
more_content: | # this will include new lines to allow paragraphs
   [Intersectional security](./_posts/intersectional), applied cryptography, privacy, tech policy and ethics,

   Preferred Languages: Rust, C++/C, Python

   Experienced speaker and writer on applied security in emerging domains




# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
